### GET city by name
GET http://localhost:8081/cities/Gizyko

### Get list of all cities
GET http://localhost:8081/cities

### Get citizens list
GET http://localhost:8081/citizens

### Delete citizen  by  id
DELETE http://localhost:8081/citizens/aa2b6af2-3c14-4784-b524-110798769d72

