### GET cities by name
GET http://localhost:8080/cities/Gizyko

### GET cities by name not exsisting
GET http://localhost:8080/cities/fsdjkbnf

### Get list of all cities
GET http://localhost:8080/cities

### Get citizens list
GET http://localhost:8080/citizens

### Get  single citizens by name
GET http://localhost:8080/citizens/Wiktor%20Czetyrbok

### Create new citizens
POST http://localhost:8080/citizens

Request Body:
{
    "name": "Kasztan",
    "age": 25,
    "citiesName": "Gizyko"
}
### Update  cities
POST http://localhost:8080/cities

Request Body:
{
    "name": "NewCity",
    "area": 100,
    "citizenssID": []
}

### Update a citizens by name (PUT method)
PUT http://localhost:8080/citizens/{{$random.uuid}}

Request Body:
{
    "name": "UpdatedName",
    "age": 30,
    "citiesName": "UpdatedCity"
}

### Update a cities by name (PUT method)
PUT http://localhost:8080/cities/{{$random.uuid}}

Request Body:
{
    "name": "UpdatedCityName",
    "area": 150,
    "citizenssID": []
}

### Delete citizens  by  id
DELETE http://localhost:8080/citizens/{{$random.uuid}}

### DELETE CITY by id
DELETE http://localhost:8080/cities/{{$random.uuid}}