### GET city by name
GET http://localhost:8080/city/Gizyko

### GET city by name not exsisting
GET http://localhost:8080/city/fsdjkbnf

### Get list of all cities
GET http://localhost:8080/city

### Get citizens list
GET http://localhost:8080/citizen

### Get  single citizen by name
GET http://localhost:8080/citizen/Wiktor%20Czetyrbok

### Create new citizen
POST http://localhost:8080/citizen

Request Body:
{
    "name": "Kasztan",
    "age": 25,
    "cityName": "Gizyko"
}
### Update  city
POST http://localhost:8080/city

Request Body:
{
    "name": "NewCity",
    "area": 100,
    "citizensID": []
}

### Update a citizen by name (PUT method)
PUT http://localhost:8080/citizen/{{$random.uuid}}

Request Body:
{
    "name": "UpdatedName",
    "age": 30,
    "cityName": "UpdatedCity"
}

### Update a city by name (PUT method)
PUT http://localhost:8080/city/{{$random.uuid}}

Request Body:
{
    "name": "UpdatedCityName",
    "area": 150,
    "citizensID": []
}

### Delete citizen  by  id
DELETE http://localhost:8080/citizen/{{$random.uuid}}

### DELETE CITY by id
DELETE http://localhost:8080/city/{{$random.uuid}}